version: '3.1'

networks:
  groots:
services:
  db:
    networks:
      groots:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    ports:
      - 3306:3306
  mongoose:
    networks:
      groots:
    image: mongo:5.0
    environment:
      - MONGO_INITDB_ROOT_USERNAME=photon
      - MONGO_INITDB_ROOT_PASSWORD=pass123
    ports:
      - 27017:27017
